Packages update
skbkontur/cassandra-thrift-client pull request #12
Opened 2020-08-20 12:50 UTC by gangstatracer

- Добавил проверку форматирования
- Обновил все пакеты

2020-08-20 13:33 UTC, AndrewKostousov requested changes

2020-08-20 13:33 UTC, AndrewKostousov commented on Cassandra.ThriftClient/Cassandra.ThriftClient.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.2.31" />
Этот пакет подключается в Directory.Build.props

2020-08-21 07:07 UTC, gangstatracer commented on Cassandra.ThriftClient/Cassandra.ThriftClient.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.2.31" />
Поправил

2020-08-21 10:56 UTC, AndrewKostousov approved these changes

2020-08-21 10:56 UTC, merged