Close connection if error occured while open
skbkontur/cassandra-thrift-client pull request #13
Opened 2020-10-02 13:00 UTC by gangstatracer

2020-10-03 12:48 UTC, AndrewKostousov requested changes

2020-10-03 12:48 UTC, AndrewKostousov commented on Cassandra.ThriftClient/Core/ThriftConnection.cs
> +                TryCloseTransport();
Как-то странно пытаться закрыть транспорт, если сдоз вызов `cassandraClient.InputProtocol.Transport.Open();`...

Я все-таки за то, чтобы по отдельности разобраться с ошибками аутентификации и переключения keyspace-а внутри `OpenTransport()`.

2020-10-05 06:25 UTC, AndrewKostousov approved these changes

2020-10-05 06:25 UTC, AndrewKostousov commented on Cassandra.ThriftClient/Core/ThriftConnection.cs
> +                logger.Error(e, "Error occured while opening thrift connection. Will try to close open transports.");
Можно здесь еще имя action-а залогировать, который сдох.

2020-10-05 06:40 UTC, gangstatracer commented on Cassandra.ThriftClient/Core/ThriftConnection.cs
> +                logger.Error(e, "Error occured while opening thrift connection. Will try to close open transports.");
Я подумал, что эта информация восстанавливается по стектрейсу, но, с именем, возможно будет проще фильтровать, поправлю

2020-10-05 06:41 UTC, AndrewKostousov commented on Cassandra.ThriftClient/Core/ThriftConnection.cs
> +                logger.Error(e, "Error occured while opening thrift connection. Will try to close open transports.");
В принципе да, стектрейса должно хватить. Если только инлайн функции не случится :-)

2020-10-05 07:35 UTC, AndrewKostousov approved these changes

2020-10-05 08:21 UTC, merged